### PR TITLE
Mpu6050 module

### PR DESCRIPTION
**Pull request by DomninDmitry-dev**
MPU6050 Practice. Kernel object module development.

### CODE REVIEW

**Comment by DomninDmitry-dev** [comment]
I have not added a module test yet.

**Comment by DomninDmitry-dev** [comment]
Task completed.

**Comment by yekovalyov** [comment]
Please make your changes in the same source file, don't create the copy of driver in another folder. It is good idea to see your changes as separate commit.

**Comment by DomninDmitry-dev** [comment]
Done.

**Pull request merged**
