### PR TITLE
Mpu6050

### PR DESCRIPTION
**Pull request by prosolvo4th**

### CODE REVIEW

**Comment by yekovalyov** [comment]
Please attach the results of performance check in text format.

**Comment by yekovalyov** [comment]
Please make your change in the same source file.

**Comment by yekovalyov** [comment]
Extension for device tree blob(DTB) is called DTB overlay, not overflow.

**Comment by prosolvo4th** [comment]
Changes: replace mpu6050.c for better comparison with the base version, rewrite commit description, add both performance tests results

**Pull request merged**
