### PR TITLE
Practice 01 mpu6050

### PR DESCRIPTION
**Pull request by prosolvo4th**

### CODE REVIEW

**Comment by yekovalyov** [comment]
You created nice application but some features are missed:
1) initialization
2) precision of output results less than provided by raw data
Also please attach the output results.

**Comment by prosolvo4th** [comment]
Changes: add write to PWR_MGMT_1 register, add proper calculating with float in bc

**Comment by yekovalyov** [comment]
Please attach the log for temperatures above 40 C.

**Comment by prosolvo4th** [comment]
Changes: fix run.sh for proper converting hex to signed short, add log with values higher than 40 degrees

**Comment by prosolvo4th** [comment]
Changes: use separated reading of temperature, add new log file

**Comment by yekovalyov** [comment]
> Changes: use separated reading of temperature, add new log file
Now it works correctly.
It looks nice and very close to minimal possible.
This version is satisfied all demands for this task.
By the way what do You think about previous version?
Do You have an idea why it showed wrong data?

**Comment by prosolvo4th** [comment]
In the previous version, I used reading two bytes, and since the low byte of temperature was specified, the low byte and a completely different byte were read, not the high byte of temperature

**Pull request merged**
